### ISSUE TITLE
Css Pseudo class support for JSS

### ISSUE THREAD

**Issue by Rishabh-Rathod** [codemodsquad/jss-codemorphs#12]
I tried converting css which had pseudo classes (like :hover)

for Example -

Css code 
```
.button {
  border: none;
  margin: 5px 10px;
  font-size: 12px;
  background: white contain no-repeat;
  transition: background color font-size;
  line-height: 1;
  transition-duration: 300ms;
}
.button:hover {
  border: 1px solid blue;
  box-shadow: 0 0 0 10px blue, 0 0 0 15px green;
}
```
Expected JSS -

```
button: {
  border: 'none',
  margin: '5px 10px',
  fontSize: 12,
  background: 'white contain no-repeat',
  transition: 'background color font-size',
  lineHeight: '1',
  transitionDuration: 300,
  '&:hover': {
  border: '1px solid blue',
  boxShadow: '0 0 0 10px blue, 0 0 0 15px green'
 },
},
```

Current Result -

```
button: {
  border: 'none',
  margin: '5px 10px',
  fontSize: 12,
  background: 'white contain no-repeat',
  transition: 'background color font-size',
  lineHeight: '1',
  transitionDuration: 300
},
'.button:hover': {
  border: '1px solid blue',
  boxShadow: '0 0 0 10px blue, 0 0 0 15px green'
},
```

**Comment by jedwards1211** [comment]
Hmmm, right now it doesn't make any effort to convert flat rules to nested.  That would be nice though

**Comment by jedwards1211** [comment]
The first step would be to convert the classes in selectors to `$`, for example

```js
'$button:hover': {
  border: '1px solid blue',
  boxShadow: '0 0 0 10px blue, 0 0 0 15px green'
},
```

**Comment by jedwards1211** [comment]
@Rishabh-Rathod I implemented the fix for at least doing `$button:hover`.  If you still want it to transform to nested `&:hover`, do you mind if we open a separate issue for that?

**Comment by jedwards1211** [comment]
I filed a related issue: #13

**Comment by Rishabh-Rathod** [comment]
> The first step would be to convert the classes in selectors to `$`, for example
> 
> ```js
> '$button:hover': {
>   border: '1px solid blue',
>   boxShadow: '0 0 0 10px blue, 0 0 0 15px green'
> },
> ```
> 
> EDIT: actually it was doing this for nested rules, but not for root rules

It does resolve issue for many cases just what is missing is #13 as you already mentioned.

i resolved it for [my use case](https://github.com/Rishabh-Rathod/css-to-js) in a [different manner ](https://github.com/Rishabh-Rathod/postcss-js/commit/a9c1bbc9845364a5f1b35cfb310029f0242c27a1) you can have a look on code 🙈   where i supported nested rules conversion.

my aim was to also help in migration to other cssinjs solution like styled-component or emotion where 
in the end i would convert 
- whole button style object to string literal and 
- also avoid camelcasing.


```
{
  flex: 1,
  padding: 10,
  backgroundColor: 'orange',
  color: colors.white,

  '&:hover': {
    backgroundColor: 'tomato',
  },
});
```

```
css`
  flex: 1;
  padding: 10px;
  background-color: orange;
  color: ${colors.white};

  &:hover {
    background-color: tomato;
  }
`
```

PS - i understand jss-codemorphs is built particular for JSS.

**Comment by jedwards1211** [comment]
@Rishabh-Rathod I added an issue for converting to nested: https://github.com/codemodsquad/jss-codemorphs/issues/15

I added a note there about how converting rules like `.foo:hover, .foo:visited { ... }` would cause a problem.
