### ISSUE TITLE
Unitless Css Styles should not be converted to string

### ISSUE THREAD

**Issue by Rishabh-Rathod** [codemodsquad/jss-codemorphs#14]
same as the [issue](https://github.com/postcss/postcss-js/issues/48)
#### Expected Behaviour 
```
css -> z-index: 1;
js -> zIndex: 1,
```

#### Actual Behaviour :- 

```
css -> z-index: 1;
js -> zIndex: '1',
```

same with flex.

JSS do not support string unitless values.

Let me know if i need to send a PR to resolve it.

**Comment by jedwards1211** [comment]
hmmm, my above fix won't take care of floating-point values for unitless properties, I'll make another fix for that
